source "https://rubygems.org"

# Use local bundle path (avoids system gem permission issues)
ENV['BUNDLE_PATH'] ||= 'vendor/bundle'

gem "fastlane", "~> 2.225"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

